########################################################################
# Basic parameters
########################################################################

# # Where to put output files
# data: data

########################################################################
# Inputs data
########################################################################

# raw, unpolished long reads
nanopore: .../long.fq.gz

# the expected size of the genome. if unset, will be computed
# automatically.
## genome_size: 5m

########################################################################
# Pipeline parameters
########################################################################

# Number of subsamples to generate of the entire long read set. If not
# set, defaults to "4".
## subsamples: 4

########################################################################
# Paths to Referenceseeker, PGAP, etc.
########################################################################

refseek_dir: ~/scratch/referenceseeker
