########################################################################
# Basic parameters
########################################################################

# Where to put output files
## data: data

# method: external
# method: flye
method: autocycler

########################################################################
# Inputs data
########################################################################

# raw, unpolished long reads
nanopore: .../long.fq.gz

# raw, unpolished Illumina reads
## short_R1: .../short_R1.fastq.gz
## short_R2: .../short_R2.fastq.gz

# the expected size of the genome. if unset, will be computed
# automatically.
## genome_size: 5m

# assemble produced externally, for method=external
## input_fasta: .../plasmidsaurus.fasta     # required
## input_gfa: .../plasmidsaurus.gfa         # optional

########################################################################
# Flye parameters
########################################################################

#flye_args: --asm-coverage 40

########################################################################
# Autocycler, Trycycler (common) parameters
########################################################################

# Number of subsamples to generate of the entire long read set. If not
# set, defaults to "4".
## subsamples: 4

# Minimum allowed read depth for subsamples
## min_read_depth: 25

########################################################################
# Trycycler
########################################################################

#cluster_args: --distance 0.01 # default
#cluster_args: --distance 0.02 # more permissive
#cluster_args: --distance 0.005 # more strict

# reconciliation parameters

#remove_contigs: H_utg000003l M_Utg998
#remove_clusters: fixme
#remove_assemblies: fixme

#reconcile_args: --max_add_seq 2000
#reconcile_args_004: --min_identity 97.0 # special case cluster_004

##MAKE_DOTPLOTS=true # make dotplots for clusters that fail to reconcile

########################################################################
# Referenceseeker: path and params
########################################################################

refseek_dir: ~/scratch/referenceseeker
#refseek_args: -a 0.95 -r
