########################################################################
# Basic parameters
########################################################################

# # Where to put output files
# data: data

########################################################################
# Inputs data
########################################################################

# raw, unpolished long reads
nanopore: .../long.fq.gz

# # raw, unpolished Illumina reads
# short_R1: .../short_R1.fastq.gz
# short_R2: .../short_R2.fastq.gz

# the expected size of the genome. if unset, will be computed
# automatically.
## genome_size: 5m

########################################################################
# Pipeline parameters
########################################################################

# Number of subsamples to generate of the entire long read set. If not
# set, defaults to "4".
## subsamples: 4

########################################################################
# Referenceseeker: path and params
########################################################################

refseek_dir: ~/scratch/referenceseeker
#refseek_args: -a 0.95 -r
